### ISSUE TITLE
Not able to edit .hic file in Juicebox

### ISSUE THREAD

**Issue by sgr308** [aidenlab/Juicebox#958]
Hi,
I assembled a genome assembly using **SALSA2** and generated a .hic file using this method:
https://github.com/marbl/SALSA#generate-hic-file-from-salsa-scaffolds

Then, I generated .agp and .assembly files using "makeAgpFromFasta.py" and "agp2assembly.py" from **juicebox_scripts.**
https://github.com/phasegenomics/juicebox_scripts/tree/master/juicebox_scripts  

First, I loaded .hic file and then I loaded .assembly file in **Juicebox_1.11.08**. The upload of both files completed without any error and I can see the **Edit, Chr** and **Scaf** on the right side **but I am not getting** **the blue, yellow and green lines** which I can see in this video at 2:00 minutes (https://www.youtube.com/watch?v=Nj7RhQZHM18).

The current .hic shows 21 scaffolds while I am expecting 19 scaffolds as this species contains 19 chromosomes. I can provide you the .hic and .assembly file for any troubleshoot.

Thanks,
Sagar

**Comment by dudcha** [comment]
Hello Sagar,

We do not offer any support for Salsa since we are not developers of that tool: my guess would be that the hic file is not in the right ‘assembly’ format.

Thanks,
Olga

**Comment by tinyfallen** [comment]
> 

Hi @dudcha

I meet the same issuse, the .hic file with black lines could not be edit. Could you please tell me how to convert it to a right ‘assembly’ format?

Many thanks!

**Comment by wan72703** [comment]
Hi,
I used the following code from juicer that generates the hic, but still used the generated file to edit the hic file.
juicer pre -a -o GQ-Y ../Build/yahs_GQ-Y.bin ../Build/yahs_GQ-Y_scaffolds_final.agp ../draft.asm.fasta.fai
asm_size=$(awk '{s+=$2} END{print s}' ../draft.asm.fasta.fai)
java -Xmx36G -jar /opt/juicer/juicer_tools.1.9.9_jcuda.0.8.jar \
    pre GQ-Y.txt GQ-Y.hic <(echo "assembly ${asm_size}")

![Image](https://github.com/user-attachments/assets/a346a62a-66c7-44d6-b81f-b8c621977925)

The two files below are the generated assembly and agp files. Due to the uploading, I modified the ending of the file.
[GQ-Y.assembly.txt](https://github.com/user-attachments/files/20971431/GQ-Y.assembly.txt)
[GQ-Y.assembly.agp.txt](https://github.com/user-attachments/files/20971432/GQ-Y.assembly.agp.txt)
